### ISSUE TITLE
Breaks Comfyui on Automatic 1111

### ISSUE THREAD

**Issue by gma-toronto** [SpenserCai/sd-webui-deoldify#11]
4 times so far, I had to reinstall Auto1111 and try again but always the same issue. 

<img width="1054" alt="Screenshot 2023-08-07 075432" src="https://github.com/SpenserCai/sd-webui-deoldify/assets/117389243/0ed58774-dd60-48aa-b1c8-6f2886ec325a">

**Comment by SpenserCai** [comment]
I have changed the default CPU to GPU for the deoldify, which may be the key issue. You can update the plugin

**Comment by gma-toronto** [comment]
> 

That took care of it, thank you!
