### ISSUE TITLE
video colorization not working

### ISSUE THREAD

**Issue by TechHalloman** [SpenserCai/sd-webui-deoldify#32]
File "C:\PORTABLE\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\PORTABLE\sd.webui\system\python\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "subprocess.py", line 969, in __init__
  File "subprocess.py", line 1438, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 500 Internal Server Error"
INFO:httpx:HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"

**Comment by SpenserCai** [comment]
you need install ffmpeg and set to PATH,if you use conda you need install it in conda

**Comment by TechHalloman** [comment]
ffmpeg installed with path and lated anaconda installed . i used windows 11

**Comment by SpenserCai** [comment]
If you use conda, make sure that ffmpeg is installed in conda, you can enter the command ffmpeg -h after switching to conda in the command interface to see if it takes effect in conda.

**Comment by TechHalloman** [comment]
ok reinstalled conda . working

**Comment by SpenserCai** [comment]
If you install the latest version of sd-webui-deoldify, then this speed is normal. I remember that it takes 1.5-2 hours to colour the 30-minute old video.
