### ISSUE TITLE
ValueError: Progress tracking requires queuing to be enabled.

### ISSUE THREAD

**Issue by claycontrast** [SpenserCai/sd-webui-deoldify#33]
安装该扩展导致 ValueError: Progress tracking requires queuing to be enabled. 您好，这个该怎样解决呢

**Comment by SpenserCai** [comment]
可以考虑更新到最新版的sd-webui。
这个报错是，之前有修改过默认配置把，报错内容是让你把sd的队列打开具体在stable-diffusion-webui中查询。
