### ISSUE TITLE
RuntimeError: unexpected EOF

### ISSUE THREAD

**Issue by w-tim** [SpenserCai/sd-webui-deoldify#35]
Hi,

I already added --disable-safe-unpickle in webui.bat as below.
%PYTHON% [launch.py](http://launch.py/) --disable-safe-unpickle %*

got error as below

RuntimeError: unexpected EOF, expected 103208165 more bytes. The file might be corrupted.
Time taken: 5.04sTorch active/reserved: 3744/3758 MiB, Sys VRAM: 5428/12282 MiB (44.19%)

**Comment by SpenserCai** [comment]
You can download the model from the huggingface address in readme, but from the error message, it seems that it is incomplete
Download and place it in the 'stable diffusion webui/models/deoldify/' directory

**Comment by w-tim** [comment]
> You can download the model from the huggingface address in readme, but from the error message, it seems that it is incomplete Download and place it in the 'stable diffusion webui/models/deoldify/' directory

It worked! Thank you for quick response and assistance.
