### ISSUE TITLE
safe uninstall

### ISSUE THREAD

**Issue by MrPwoz** [SpenserCai/sd-webui-deoldify#36]
how can I safely unistall the extension whithout using the Automatic1111 UI?
After the installation the UI does not work any more and Stable Diffusion crashes on startup so I need to remove the whole Deoldify to try to recover my functioning installation of SD.
I've noticed that the "delete the extension folder" method does not work here, so there has to be some more thing to be kept in mind when trying to remove.

**Comment by SpenserCai** [comment]
In fact, all extensions do not have a so-called secure uninstallation, and currently no users have reported the situation you mentioned. If you have a complete error message, please send and reopen this issue
