### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by myB0B** [SpenserCai/sd-webui-deoldify#37]
sdxl automatic1111 on windows 11
install deoldify from extentions
go to extras and check deoldfy box
import jpeg image
click generate
result is : TypeError: 'NoneType' object is not subscriptable

(no error if i uncheck deoldify)

**Comment by myB0B** [comment]
found it 👍 
miss to add --disable-safe-unpickle in startup

**Comment by techlab4kids-apps** [comment]
I have the same problem.
I dont' undestand what "add --disable-safe-unpickle in startup" means.
Which file should I have to modify?
Thanks

**Comment by myB0B** [comment]
edit the file webui-user.bat and add to it to commandline_args:

`set COMMANDLINE_ARGS= --disable-safe-unpickle`
