### ISSUE TITLE
Windows 10 Confirmation

### ISSUE THREAD

**Issue by aleph23** [SpenserCai/sd-webui-deoldify#38]
Thank you for this, BTW.

Just wanted to let you know that it's also working on Windows 10 (22H2) w/ Python 3.10.6 & Torch 2.0.1+cu118, Torchvision 0.15.2, Pillow 9.5.0, & opencv-python 4.8.0.76

Artistic and Pre-decolor enabled
![2023-09-27_135940](https://github.com/SpenserCai/sd-webui-deoldify/assets/10507562/2820e933-67c2-4462-aaa9-d40888490569)

Stable model, no pre-decolor
![2023-09-27_141219](https://github.com/SpenserCai/sd-webui-deoldify/assets/10507562/f9770aab-cda9-48f2-9ef2-75098260706c)
(Sorry, no fork, so I can't PR as requested)

**Comment by SpenserCai** [comment]
The fading algorithm will be optimized in the future, and several users have reported that photos with yellowing will have better color effects after fading.
