### ISSUE TITLE
Only Video section 视频 under the DeOldify TAG in SD WebUI?

### ISSUE THREAD

**Issue by pendave** [SpenserCai/sd-webui-deoldify#45]
I can see only video section, just like 
![image](https://github.com/SpenserCai/sd-webui-deoldify/assets/1331881/ab135aca-9b4b-4862-a88c-fcfee22ba68a)

where's the image section for coloring?

**Comment by spinferno** [comment]
it's hard to guess, but the image deoldify is placed at the bottom of the 'extras' tab 
![2024-01-01 11_01_50-Stable Diffusion](https://github.com/SpenserCai/sd-webui-deoldify/assets/12758205/aa0bd3b1-2179-4883-9bd0-95065c8dbcf6)

**Comment by SpenserCai** [comment]
> it's hard to guess, but the image deoldify is placed at the bottom of the 'extras' tab ![2024-01-01 11_01_50-Stable Diffusion](https://private-user-images.githubusercontent.com/12758205/293525746-aa0bd3b1-2179-4883-9bd0-95065c8dbcf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDc1MjIsIm5iZiI6MTcwNDQ0NzIyMiwicGF0aCI6Ii8xMjc1ODIwNS8yOTM1MjU3NDYtYWEwYmQzYjEtMjE3OS00ODgzLTliZDAtOTUwNjVjOGRiY2Y2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA5MzM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NTVkNTRkNjAxYWEyM2Q0MjFlOGM3NjAyMzAxMzAyMzJkYjQ2YjcwMTE5ZjQ3MDhkNTMwY2ViOWQ0NmQ3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1cpY3xiq6pfLrsA_E1hOQlT2tefIjPLVGRud0Igop8Q)

it's true
