### ISSUE TITLE
Can not run launch.py

### ISSUE THREAD

**Issue by laowalter** [SpenserCai/sd-webui-deoldify#50]
In linux, 

python launch.py
Traceback (most recent call last):
  File "/home/quant/myapps/oldphotos/stable-diffusion-webui/launch.py", line 1, in <module>
    from modules import launch_utils
ImportError: cannot import name 'launch_utils' from 'modules' (/home/abc/.virtualenvs/oldphotos/lib/python3.11/site-packages/modules.py)

Thanks.

**Comment by SpenserCai** [comment]
it's stable diffusion webui's extension,not independent program
