### ISSUE TITLE
no output image 

### ISSUE THREAD

**Issue by TechHalloman** [SpenserCai/sd-webui-deoldify#6]
TypeError: 'NoneType' object is not subscriptable

Time taken: 1 min. 5.7 sec.

A: 3.27 GB, R: 4.06 GB, Sys: 4.0/4 GB (100.0%)

**Comment by SpenserCai** [comment]
add start command --disable-safe-unpickle

check stable-diffusion-webui/models/deoldify/*.pth

**Comment by SpenserCai** [comment]
if your vram is 4GB maybe not enough

**Comment by TechHalloman** [comment]
add start command --disable-safe-unpickle

working thank you

**Comment by SpenserCai** [comment]
> add start command --disable-safe-unpickle
> 
> 
> 
> working thank you

Have a good time.
